### ISSUE TITLE
Echo on android mobile issue

### ISSUE THREAD

**Issue by Elleyes** [LearnersGuild/los#103] opened 2016-10-31 18:14 UTC
### Expected vs. Actual

_Login issue with rocket chat for android mobile (I have a one+one) using my github account.  Github does not have login for android mobile. Rocket chat cannot log me into my github account from my android mobile.

### Steps to Reproduce

_Downloaded rocket chat app for android. Failed attempt through github login prompt. Does not connect. Page hangs, no error message.

### Environment and Versions

_Mobile phone is one+one android

**Comment by jeffreywescott** [comment] 2016-12-13 19:27
Duplicate of #97.

**Closed as completed by jeffreywescott** 2016-12-13 19:27 UTC
Labels: bug
