### ISSUE TITLE
Missing Channels in Nav Panel using Rocket.Chat+ Desktop

### ISSUE THREAD

**Issue by Compsight** [LearnersGuild/los#131] opened 2016-12-13 17:39 UTC
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
Attempting to use/view Echo using Rocket.Chat+ for macOS X.
Upon opening and logging in (?after session timeout?), all "normal" channels are missing. Only channels that have been marked as favorite are showing on the left-hand navigation panel.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
This problem is intermittent. No steps to reproduce.
Problem seems to be solved by logging out (clicking on profile pic in nav panel) and logging in again.

Note: This problem is NOT solved by:
1. uninstall/reinstall of Rocket.Chat+ app
2. restart of OS
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_
Rocket.Chat+ 1.3.1 (15)
macOS Sierra 10.12.1
MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by heyheyjp** [comment] 2016-12-13 18:45
@Compsight: please attach a screenshot if you have one/next time this occurs. Thanks!

**Comment by jeffreywescott** [comment] 2016-12-13 19:31
Duplicate of #130

**Closed as completed by jeffreywescott** 2016-12-13 19:31 UTC
Labels: bug
