### ISSUE TITLE
Android app will not log in

### ISSUE THREAD

**Issue by arayi** [LearnersGuild/los#129] opened 2016-12-13 17:26 UTC
### Expected vs. Actual

Log into Echo/Rocket via Android app

### Steps to Reproduce

Consistent errors when attempting to log in via Android on various phones/OS versions

### Environment and Versions

Not sure how extensive, but have heard consistent complaints from other Android users

**Comment by heyheyjp** [comment] 2016-12-13 17:28
Related: https://github.com/RocketChat/Rocket.Chat/issues/5014.

**Comment by jeffreywescott** [comment] 2016-12-13 19:27
Duplicate of #97.

**Closed as completed by jeffreywescott** 2016-12-13 19:27 UTC
Labels: bug
