### ISSUE TITLE
Auto-archive old Echo channels each week

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#99] opened 2016-10-26 21:25 UTC
### Expected vs. Actual

There are way too many echo channels to search through when I want to go looking for relevant channels to join. This creates a lot of extra noise and dilutes the potency / relevance of communication via Echo, which is already a problem.

Suggested solution: auto-archive channels from the previous cycle as soon as a new cycle is launched. Ideally, they are still searchable for the people who were in the channels and on those projects, but they aren't cluttering up the channel list for everyone.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by heyheyjp** [comment] 2016-10-26 21:41
Duplicate of https://github.com/LearnersGuild/los/issues/57.

**Closed as completed by heyheyjp** 2016-10-26 21:41 UTC
