### ISSUE TITLE
`/project list -r` broken

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/los#127] opened 2016-12-07 18:52 UTC
![image](https://cloud.githubusercontent.com/assets/8385/20981930/4a56c1ec-bc6b-11e6-8a80-e8c07a36d1c7.png)

**Comment by heyheyjp** [comment] 2016-12-07 20:20
Duplicate of https://github.com/LearnersGuild/los/issues/122.

**Closed as completed by heyheyjp** 2016-12-07 20:20 UTC
