### ISSUE TITLE
Mouse wheel effecting integer fields in retros

### ISSUE THREAD

**Issue by mKleinCreative** [LearnersGuild/los#144] opened 2017-01-03 16:56 UTC
### Expected vs. Actual

When trying to scroll down on the page when you're in the retrospective survey at the page where you're filling in hours or where your zpd was at and you have the field selected, it tends to go a little wild and change your score.
### Steps to Reproduce

So in the retrospective survey, get into the section where you update your zpd and est amount of hours then click the field and scroll up or down. what happens usually is someone will fill this field out then try to use either the laptop track pad or the mouse wheel to scroll up or down. the number will go into either the negative area or high up there into the hundreds.

### Environment and Versions

Google Chrome
Version 55.0.2883.95 (64-bit)

**Comment by jeffreywescott** [comment] 2017-01-03 19:18
Duplicate of #85.

**Closed as completed by jeffreywescott** 2017-01-03 19:18 UTC
