### ISSUE TITLE
Private channels don't automatically add members

### ISSUE THREAD

**Issue by carlabagdonas** [LearnersGuild/los#67] opened 2016-09-06 05:44 UTC
### Expected vs. Actual

I've noticed that when I create a private channel, even though I invite people to it, it won't show up in their channel sidebar unless they search for the channel within private channels, or unless I tag them in the channel. I think ideally, if you create a private channel with a group of people, it should automatically show up in their sidebar menu. i.e. it should "pull them in" to the channel, instead of waiting for them to opt in.
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by jeffreywescott** [comment] 2016-09-06 15:45
Duplicate of #34. Closing.

**Closed as completed by jeffreywescott** 2016-09-06 15:45 UTC
