### ISSUE TITLE
Chat window profile buggy when hovering

### ISSUE THREAD

**Issue by matthewLG** [LearnersGuild/los#3] opened 2016-07-01 18:11 UTC
![screen shot 2016-07-01 at 11 08 47 am](https://cloud.githubusercontent.com/assets/20246958/16530360/9c4b2f0e-3f7c-11e6-8842-b9573bfe3a65.png)
### Expected vs. Actual

_What were you attempting to do? What actually happened?_
### Steps to Reproduce

_How can you reproduce the bug? Include as much detail as you can._
### Environment and Versions

_What versions of relevant external software were you using (browser, OS, etc.)?_

**Comment by matthewLG** [comment] 2016-07-01 18:12
look at tanner

**Comment by matthewLG** [comment] 2016-07-01 18:49
also check out the Direct Message insect

**Comment by bundacia** [comment] 2016-07-05 14:58
duplicate of ~~#3~~ #4

**Closed as completed by bundacia** 2016-07-05 14:58 UTC

**Comment by heyheyjp** [comment] 2016-07-05 15:39
@bundacia: lol, wat? this is a duplicate of itself? :)

**Comment by bundacia** [comment] 2016-07-05 16:12
Doh! Duplicate of #4
